# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec for TeslaCam Viewer
# Build: python -m PyInstaller TeslaCamViewer.spec

from pathlib import Path
import sys

ROOT = Path(SPECPATH)

# Bundle the imageio_ffmpeg binary so the export feature works without system FFmpeg
try:
    import imageio_ffmpeg as _iio
    _ffmpeg_exe = Path(_iio.get_ffmpeg_exe())
    _extra_binaries = [(str(_ffmpeg_exe), "imageio_ffmpeg/binaries")]
except Exception:
    _extra_binaries = []

a = Analysis(
    [str(ROOT / "main.py")],
    pathex=[str(ROOT)],
    binaries=_extra_binaries,
    datas=[
        # Ship the QSS theme and app icon alongside the executable
        (str(ROOT / "resources" / "style.qss"), "resources"),
        (str(ROOT / "resources" / "icon.png"),  "resources"),
        # Third-party license notices (LGPL compliance)
        (str(ROOT / "LICENSES"),                "LICENSES"),
    ],
    hiddenimports=[
        # Qt Multimedia — needed for QMediaPlayer / QVideoWidget
        "PySide6.QtMultimedia",
        "PySide6.QtMultimediaWidgets",
        # SVG renderer — needed for inline SVG icons
        "PySide6.QtSvg",
        "PySide6.QtSvgWidgets",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Trim unused heavy Qt modules to keep the bundle smaller
        "PySide6.Qt3DAnimation",
        "PySide6.Qt3DCore",
        "PySide6.Qt3DExtras",
        "PySide6.Qt3DInput",
        "PySide6.Qt3DLogic",
        "PySide6.Qt3DRender",
        "PySide6.QtCharts",
        "PySide6.QtDataVisualization",
        "PySide6.QtQuick",
        "PySide6.QtQuickControls2",
        "PySide6.QtQuickWidgets",
        "PySide6.QtWebEngine",
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebChannel",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="TeslaCamViewer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,            # no black console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "resources" / "icon.ico"),  # generated by build.ps1
    version=str(ROOT / "resources" / "version.txt") if (ROOT / "resources" / "version.txt").exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="TeslaCamViewer",
)
